<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Adapter\**" />
    <Compile Remove="Utils\**" />
    <EmbeddedResource Remove="Adapter\**" />
    <EmbeddedResource Remove="Utils\**" />
    <None Remove="Adapter\**" />
    <None Remove="Utils\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\ILogProvider.cs" />
    <Compile Remove="Models\LogLevelEnum.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Logging\LoggerHelper.cs.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\" />
  </ItemGroup>

</Project>
