<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="VideoDownloader.cs.txt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Veyrin.Core\Veyrin.Core.csproj" />
  </ItemGroup>

</Project>
